export type DecayProfileSeed = {
  key: string;
  attributeSlug: string;
  graceDays: number;
  decayPerDay: number;
  baseDecayPerDayAfterDays: number;
  baseDecayPerDay: number;
  floorRatio: number;
  maintenanceBoostCurrent: number;
  maintenanceBoostBase: number;
  maintenanceBoostPotential: number;
  recoveryBoostCurrent: number;
  recoveryBoostBase: number;
  recoveryBoostPotential: number;
};

export const DECAY_PROFILE_SEEDS: readonly DecayProfileSeed[] = [
  {
    key: "focus-default",
    attributeSlug: "focus",
    graceDays: 2,
    decayPerDay: 0.18,
    baseDecayPerDayAfterDays: 14,
    baseDecayPerDay: 0.02,
    floorRatio: 0.55,
    maintenanceBoostCurrent: 0.25,
    maintenanceBoostBase: 0.04,
    maintenanceBoostPotential: 0.02,
    recoveryBoostCurrent: 0.06,
    recoveryBoostBase: 0,
    recoveryBoostPotential: 0,
  },
  {
    key: "discipline-default",
    attributeSlug: "discipline",
    graceDays: 3,
    decayPerDay: 0.1,
    baseDecayPerDayAfterDays: 18,
    baseDecayPerDay: 0.015,
    floorRatio: 0.6,
    maintenanceBoostCurrent: 0.22,
    maintenanceBoostBase: 0.05,
    maintenanceBoostPotential: 0.025,
    recoveryBoostCurrent: 0.04,
    recoveryBoostBase: 0,
    recoveryBoostPotential: 0,
  },
  {
    key: "energy-default",
    attributeSlug: "energy",
    graceDays: 1,
    decayPerDay: 0.2,
    baseDecayPerDayAfterDays: 16,
    baseDecayPerDay: 0.018,
    floorRatio: 0.52,
    maintenanceBoostCurrent: 0.2,
    maintenanceBoostBase: 0.03,
    maintenanceBoostPotential: 0.015,
    recoveryBoostCurrent: 0.24,
    recoveryBoostBase: 0.02,
    recoveryBoostPotential: 0.01,
  },
  {
    key: "organization-default",
    attributeSlug: "organization",
    graceDays: 4,
    decayPerDay: 0.09,
    baseDecayPerDayAfterDays: 21,
    baseDecayPerDay: 0.012,
    floorRatio: 0.62,
    maintenanceBoostCurrent: 0.18,
    maintenanceBoostBase: 0.04,
    maintenanceBoostPotential: 0.02,
    recoveryBoostCurrent: 0.03,
    recoveryBoostBase: 0,
    recoveryBoostPotential: 0,
  },
  {
    key: "resilience-default",
    attributeSlug: "resilience",
    graceDays: 6,
    decayPerDay: 0.06,
    baseDecayPerDayAfterDays: 30,
    baseDecayPerDay: 0.01,
    floorRatio: 0.66,
    maintenanceBoostCurrent: 0.15,
    maintenanceBoostBase: 0.04,
    maintenanceBoostPotential: 0.025,
    recoveryBoostCurrent: 0.07,
    recoveryBoostBase: 0.01,
    recoveryBoostPotential: 0,
  },
  {
    key: "memory-default",
    attributeSlug: "memory",
    graceDays: 4,
    decayPerDay: 0.11,
    baseDecayPerDayAfterDays: 20,
    baseDecayPerDay: 0.014,
    floorRatio: 0.6,
    maintenanceBoostCurrent: 0.2,
    maintenanceBoostBase: 0.035,
    maintenanceBoostPotential: 0.02,
    recoveryBoostCurrent: 0.02,
    recoveryBoostBase: 0,
    recoveryBoostPotential: 0,
  },
  {
    key: "creativity-default",
    attributeSlug: "creativity",
    graceDays: 5,
    decayPerDay: 0.08,
    baseDecayPerDayAfterDays: 24,
    baseDecayPerDay: 0.012,
    floorRatio: 0.58,
    maintenanceBoostCurrent: 0.22,
    maintenanceBoostBase: 0.03,
    maintenanceBoostPotential: 0.03,
    recoveryBoostCurrent: 0.05,
    recoveryBoostBase: 0,
    recoveryBoostPotential: 0.005,
  },
  {
    key: "leadership-default",
    attributeSlug: "leadership",
    graceDays: 6,
    decayPerDay: 0.07,
    baseDecayPerDayAfterDays: 26,
    baseDecayPerDay: 0.011,
    floorRatio: 0.61,
    maintenanceBoostCurrent: 0.19,
    maintenanceBoostBase: 0.045,
    maintenanceBoostPotential: 0.02,
    recoveryBoostCurrent: 0.02,
    recoveryBoostBase: 0,
    recoveryBoostPotential: 0,
  },
  {
    key: "emotional-control-default",
    attributeSlug: "emotional-control",
    graceDays: 5,
    decayPerDay: 0.09,
    baseDecayPerDayAfterDays: 22,
    baseDecayPerDay: 0.013,
    floorRatio: 0.6,
    maintenanceBoostCurrent: 0.17,
    maintenanceBoostBase: 0.04,
    maintenanceBoostPotential: 0.02,
    recoveryBoostCurrent: 0.12,
    recoveryBoostBase: 0.01,
    recoveryBoostPotential: 0.005,
  },
  {
    key: "physical-endurance-default",
    attributeSlug: "physical-endurance",
    graceDays: 7,
    decayPerDay: 0.05,
    baseDecayPerDayAfterDays: 28,
    baseDecayPerDay: 0.01,
    floorRatio: 0.65,
    maintenanceBoostCurrent: 0.2,
    maintenanceBoostBase: 0.035,
    maintenanceBoostPotential: 0.02,
    recoveryBoostCurrent: 0.11,
    recoveryBoostBase: 0.015,
    recoveryBoostPotential: 0.005,
  },
] as const;
