export const ONBOARDING_EMPHASIS_CURRENT_DELTA = 0.6;
export const ONBOARDING_EMPHASIS_BASE_DELTA = 0.24;
export const ONBOARDING_EMPHASIS_POTENTIAL_DELTA = 0.32;

export const ONBOARDING_BACKGROUND_CURRENT_DELTA = -0.35;
export const ONBOARDING_BACKGROUND_BASE_DELTA = -0.12;
export const ONBOARDING_BACKGROUND_POTENTIAL_DELTA = -0.08;
